### ISSUE TITLE
Fix TextSourceApp error with file-based configuration

### ISSUE THREAD

**Issue by csjx** [csjx/realtime-data#26]
When using an instrument XML configuration file using a `file` connection type:
```xml
    <connectionType>socket</connectionType>
    <connectionParams>
        <filePath>/home/kilonalu/PIMI01_001CTDXXXXR00_latest_data.txt</filePath>
    </connectionParams>
```
we get an exception of:

```
Exception in thread "main" java.util.NoSuchElementException: 'connectionParams.hostPort' doesn't map to an existing object
	at org.apache.commons.configuration.AbstractConfiguration.getInt(AbstractConfiguration.java:813)
	at edu.hawaii.soest.pacioos.text.configure.Configuration.getHostPortConnectionParam(Configuration.java:712)
	at edu.hawaii.soest.pacioos.text.TextSourceFactory.getSimpleTextSource(TextSourceFactory.java:73)
	at edu.hawaii.soest.pacioos.text.TextSourceApp.main(TextSourceApp.java:57)
```

So the `Configuration` is expecting a host port connection param, when there is none.  This should be instantiating a `FileTextSource` class rather than a `SocketTextSource`, so check that first.  This could just be a configuration issue too.

**Comment by csjx** [comment]
This in fact was a configuration issue. Closing.
