### ISSUE TITLE
Update the manage-instruments script to bulk load instrument data into the Data Turbine

### ISSUE THREAD

**Issue by csjx** [csjx/realtime-data#40]
Now that the `TextRebuildApp` is refactored and we have a `TextRebuilder` class, create a `TextLoaderApp` that grabs the latest year from the raw instrument archive and reloads it into the Data Turbine for both the `DecimalASCIISampleData` and the `PacIOOS2020Format` channels.  Fold this app into the `manage-instruments` script by introducing `-c reloader -i {instrument}` options.  This will be used after an instrument archive is rebuilt to get the data in the DT up to date.

**Comment by csjx** [comment]
The `TextLoaderApp` is complete and tested, and I'm now adding it into the `manage-instruments` script.

**Comment by csjx** [comment]
This is complete, but in testing, I'm seeing an sample ordering issue with `MU01XX_001YCTDXXXR00` data:
```
<28-Dec-2021 MST 00:05:32.940> <MU01XX_001YCTDXXXR00>
   Reconnected with the following channels:
   	DecimalASCIISampleData
   	PacIOOS2020Format
<28-Dec-2021 MST 00:05:33.708> <MU01XX_001YCTDXXXR00>
   Cannot add frame to MU01XX_001YCTDXXXR00, it starts before the end of the previous frame.
   	End of previous frame: 1.461106255E9	Start of new frame: 1.429570267E9
```

but loading all of the data from `AW02XX_001CTDXXXXR00` worked fine, so this may be a sorting issue with space-delimited data. Looking into it.

The Data Turbine exception:
```
<28-Dec-2021 MST 00:05:33.708> <MU01XX_001YCTDXXXR00>
   Cannot add frame to MU01XX_001YCTDXXXR00, it starts before the end of the previous frame.
   	End of previous frame: 1.461106255E9	Start of new frame: 1.429570267E9
<28-Dec-2021 MST 00:05:33.710> <MU01XX_001YCTDXXXR00>
   java.io.FileNotFoundException: /tmp/dt/MU01XX_001YCTDXXXR00/RB1/reghdr.rbn (No such file or directory)
   	at java.base/java.io.FileOutputStream.open0(Native Method)
   	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
   	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
   	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:123)
   	at com.rbnb.api.Archive.writeToArchive(Archive.java:1685)
   	at com.rbnb.api.RingBuffer.writeToArchive(RingBuffer.java:3470)
   	at com.rbnb.api.RBO.writeToArchive(RBO.java:8526)
   	at com.rbnb.api.RBO.doShutdown(RBO.java:2672)
   	at com.rbnb.api.RBO.run(RBO.java:6135)
   	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by csjx** [comment]
Some more documentation on this - the sorted summary table:
```
20211228-00:05:32: [INFO]: Reloading the latest year of data into the Data Turbine:
                                                           table
  C1    |   C2    |   C3    |   C4    |   C5   |   C6    |   C7    |   C8    |   C9   |  C10  |       datetimesInUTC       |
----------------------------------------------------------------------------------------------------------------------------
 24.56  |  50.01  |  33.07  |  2.130  |  6.37  |  475.3  |  141.9  |   99.3  |  6.85  |  7.0  |  2015-04-20T22:51:07.000Z  |
 24.86  |  50.31  |  33.07  |  2.302  |  6.37  |  386.7  |  160.0  |  105.2  |  7.22  |  7.0  |  2015-04-21T00:01:07.000Z  |
 24.57  |  49.89  |  32.97  |  2.375  |  6.37  |  525.9  |  148.3  |  100.1  |  6.91  |  7.0  |  2015-04-21T00:11:07.000Z  |
 24.56  |  49.28  |  32.52  |  2.415  |  6.37  |  380.1  |  134.7  |  100.3  |  6.94  |  7.0  |  2015-04-21T00:21:07.000Z  |
 24.57  |  49.60  |  32.75  |  2.376  |  6.36  |  545.3  |  153.3  |  100.4  |  6.94  |  7.0  |  2015-04-21T00:31:07.000Z  |
 24.56  |  49.77  |  32.89  |  2.436  |  6.36  |  492.9  |  150.4  |  101.5  |  7.01  |  7.0  |  2015-04-21T00:41:07.000Z  |
 24.52  |  50.40  |  33.38  |  2.419  |  6.37  |  440.1  |  102.7  |  100.9  |  6.95  |  7.0  |  2015-04-21T00:51:07.000Z  |
 24.52  |  50.02  |  33.10  |  2.476  |  6.36  |  382.9  |  107.4  |  100.4  |  6.93  |  7.0  |  2015-04-21T01:01:07.000Z  |
 24.54  |  49.58  |  32.76  |  2.465  |  6.37  |  479.6  |  182.0  |  100.1  |  6.92  |  7.0  |  2015-04-21T01:11:07.000Z  |
 24.54  |  49.79  |  32.92  |  2.450  |  6.37  |  580.8  |  180.0  |   99.4  |  6.87  |  7.0  |  2015-04-21T01:21:07.000Z  |
   ...  |    ...  |    ...  |    ...  |   ...  |    ...  |    ...  |    ...  |   ...  |  ...  |                       ...  |
 24.89  |  42.61  |  27.45  |  1.900  |  8.39  |  234.7  |  568.5  |   92.5  |  6.55  |  6.0  |  2016-04-19T21:20:55.000Z  |
 24.87  |  42.73  |  27.54  |  1.917  |  8.39  |  218.2  |  568.5  |   94.8  |  6.71  |  5.9  |  2016-04-19T21:30:55.000Z  |
 24.87  |  45.59  |  29.61  |  1.922  |  8.40  |  210.6  |  568.5  |   95.5  |  6.68  |  5.9  |  2016-04-19T21:40:55.000Z  |
 24.88  |  44.30  |  28.67  |  1.965  |  8.39  |  218.0  |  568.5  |   95.3  |  6.70  |  5.9  |  2016-04-19T21:50:55.000Z  |
 24.89  |  43.77  |  28.28  |  1.969  |  8.40  |  238.9  |  568.5  |   94.8  |  6.69  |  5.9  |  2016-04-19T22:00:55.000Z  |
 24.93  |  43.73  |  28.23  |  1.952  |  8.39  |  227.2  |  568.5  |   95.5  |  6.73  |  5.9  |  2016-04-19T22:10:55.000Z  |
 24.90  |  43.41  |  28.02  |  1.970  |  8.39  |  206.5  |  568.5  |   95.0  |  6.71  |  5.9  |  2016-04-19T22:20:55.000Z  |
 24.91  |  43.46  |  28.04  |  2.007  |  8.39  |  204.4  |  568.5  |   95.7  |  6.75  |  5.9  |  2016-04-19T22:30:55.000Z  |
 24.99  |  43.48  |  28.01  |  2.031  |  8.40  |  229.3  |  568.5  |   94.4  |  6.66  |  5.9  |  2016-04-19T22:40:55.000Z  |
 25.12  |  43.55  |  27.98  |  1.978  |  8.40  |  192.2  |  568.5  |   97.3  |  6.84  |  5.9  |  2016-04-19T22:50:55.000Z  |
```

**Comment by csjx** [comment]
The sample in question came after the  date`1461106255` in seconds since the unix epoch:
```bash
❯ date -r 1461106255 +%Y-%m-%d'T'%H:%M:%S'Z'
2016-04-19T16:50:55Z
```
and the offending date was:
```
❯ date -r 1429570267 +%Y-%m-%d'T'%H:%M:%S'Z'
2015-04-20T16:51:07Z
```

But after looking at the data, and re-running the `reloader` command several times, it worked as expected.  So I may have had my local DT a bit jacked up. Closing this.
