### ISSUE TITLE
Data Turbine archivers not writing

### ISSUE THREAD

**Issue by csjx** [csjx/realtime-data#57]
From John:

I noticed the other two near real-time sensors, NS04 (WK02XX) and NS10 (MB01XX_001), are also stuck in DT processed compared to DT raw. Each about a month behind present:

NS04 (WK02XX)
https://realtime.pacioos.hawaii.edu/pacioos-processed-data/WK02XX_001CTDXXXXR00/
https://realtime.pacioos.hawaii.edu/pacioos-raw-data/alawai/WK02XX_001CTDXXXXR00/DecimalASCIISampleData/

NS10 (MB01XX_001)
https://realtime.pacioos.hawaii.edu/pacioos-processed-data/MB01XX_001CTDXXXXR00/
https://realtime.pacioos.hawaii.edu/pacioos-raw-data/alawai/MB01XX_001CTDXXXXR00/DecimalASCIISampleData/

----

For this issue of the archive files falling behind, I’ve done a bunch of testing of my code and it’s working as expected, but I’m seeing an error coming from the Data Turbine that looks to be the cause.  Basically, at the top of the hour, or the top of the day, the archivers call “fetch” to get the hourly or daily data from the DT and they write them to disk.  In DT parlance, this returns a channel map, with each channel of sample data indexed as 0, 1, etc.  I’m seeing error log entries where the data channel index is -1, meaning no channels of data were returned, e.g.:

[DEBUG] 2020-12-24 09:59:59,544 (FileArchiverSink:exportData:1047) Channel index is: -1

The archiver retries the fetch call 10 times before giving up.  The only solution I have found is to restart the Data Turbine with:

sudo service rbnb stop
sudo service rbnb start

I’m not sure why the DT isn’t responding correctly to the fetch requests, but after a restart, it works fine.  We are using the latest and final version of the DT, so I don’t expect the developers be making any patches or changes.  As I said a while back, a move to a more recent and maintained streaming engine like Apache Kafka or RabbitMQ would undoubtedly help, but would take effort.

**Comment by csjx** [comment]
In testing the daily archiver locally, I'm seeing an exception:
```
Exception in thread "Timer-1" java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because the return value of "edu.hawaii.soest.pacioos.text.convert.RawToPacIOOS2020Converter.getDateFields()" is null
	at edu.hawaii.soest.pacioos.text.convert.RawToPacIOOS2020Converter.parse(RawToPacIOOS2020Converter.java:165)
	at edu.hawaii.soest.kilonalu.utilities.FileArchiverSink.exportData(FileArchiverSink.java:1069)
	at edu.hawaii.soest.kilonalu.utilities.FileArchiverSink.runWork(FileArchiverSink.java:968)
	at edu.hawaii.soest.kilonalu.utilities.FileArchiverSink.export(FileArchiverSink.java:901)
	at edu.hawaii.soest.pacioos.text.TextSinkApp$1.run(TextSinkApp.java:105)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)```

So I'm tracking this issue down.

**Comment by csjx** [comment]
When the `TextSinkApp` configures a new `RawToPacIOOS2020Converter` and adds configuration properties from the XML config file, it was missing the `dateFields` and `dateFormats` fields.  When the scheduled thread would run, it was throwing an exception of getting `null` back when looking up these calls, but being in a dedicated `Timer` thread, the exception was not being logged. This is fixed now, so I'm closing the ticket.
